baseurl = "https://guiunoh.github.io"
languageCode = 'ko-kr'
title = "Blog"
paginate = 10
theme =  ["github.com/Vimux/Amnix"]

[Params]
  description = "Responsive and configurable Hugo theme"
  columns = 2
  copyright = "guiunoh"
  copyrightStartYear = 2023
  mainSections = ['posts']

[Params.Entry]
  meta = ["date"]

[Params.Sidebar]
  widgets = ["recent", "categories", "tags"]

[Params.Widgets]
  recentDate = true